# ---------- Build ----------
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json tsconfig.lambda.json ./
COPY quotes.json ./
COPY src/getQuote.ts ./src/getQuote.ts
COPY src/localInvoke.ts ./src/localInvoke.ts

RUN npm install
RUN npx tsc --project tsconfig.lambda.json

# ---------- Runtime ----------
FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/quotes.json ./

CMD ["node", "dist/getQuote.js"]
